name: marapp
description: "Mara's sweets and savories app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  provider: ^6.0.1
  google_sign_in: ^6.0.1
  flutter_signin_button: ^2.0.0
  logger: ^2.0.2+1
  universal_io: ^2.0.5
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  flutter_native_splash: ^2.2.14
  image_picker: ^0.8.5+3
  http: any
  cached_network_image: ^3.2.0
  image: ^4.0.17
  html: any
  geolocator: ^13.0.2
  flutter_typeahead: ^5.0.1
  flutter_keyboard_visibility: ^6.0.0
  firebase_auth_web: ^5.8.12
  js: any
  intl: any
  emailjs: ^4.0.0
  flutter_dotenv: ^5.0.2
  firebase_messaging: any
  flutter_local_notifications: any



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any
  flutter_lints: any

flutter_launcher_icons:
  image_path: "assets/marapp.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/marapp.png"
    file_name: "splash/img"
  macos:
    generate: true
    image_path: "assets/marapp.png"

flutter_native_splash:
  color: "#ffffff" # Colore di sfondo dello splash screen
  image: assets/marapp.png # Immagine del logo
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/marapp.png
    - assets/icon.webp
    - assets/food_photos/
